In [3]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC

# Part1

In [4]:
columns = np.arange(5000)

In [7]:
data_train = pd.read_csv('gisette_train.data', sep = " ", names= columns, index_col=False)

In [8]:
data_train.head()

0     1     2     3     4     5     6     7     8     9     ...  4990  \
0   550     0   495     0     0     0     0   976     0     0  ...     0   
1     0     0     0     0     0     0     0   976     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0   742     0     0     0     0   684     0   956  ...     0   
4     0     0     0     0     0     0     0   608     0   979  ...   991   

   4991  4992  4993  4994  4995  4996  4997  4998  4999  
0     0     0   991   991     0     0     0     0   983  
1   475     0   991     0     0   991     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0   674     0     0   838  
4     0     0   828     0     0     0     0     0     0  

[5 rows x 5000 columns]

In [9]:
train_labels = pd.read_csv('gisette_train.labels', names = ['label'])
train_labels.head()

label
0      1
1     -1
2      1
3      1
4      1

In [10]:
test_labels = pd.read_csv('gisette_valid.labels', names = ['label'])

In [11]:
data_test = pd.read_csv('gisette_valid.data', sep = " ", names= columns, index_col=False)

In [12]:
data_test.head()

0     1     2     3     4     5     6     7     8     9     ...  4990  \
0   688     0     0     0     0     0     0   952     0   870  ...     0   
1   778   758     0     0     0     0     0   708     0   991  ...     0   
2   469     0   816     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0   571   991   983     0   983  ...     0   
4     0     0     0     0     0     0     0   949     0   991  ...     0   

   4991  4992  4993  4994  4995  4996  4997  4998  4999  
0     0     0     0     0     0   494     0   769     0  
1     0     0   770     0     0     0     0     0     0  
2     0     0   467     0     0     0   417     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0   976     0  

[5 rows x 5000 columns]

In [13]:
from sklearn.svm import SVC
model = SVC(kernel="linear")

In [14]:
model.fit(data_train, train_labels)

D:\Anaconda path\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='linear')

In [15]:
no_of_support_vectors = model.support_vectors_ 
print(len(no_of_support_vectors))
print(no_of_support_vectors)

1084
[[  0.   0. 983. ...   0.   0.   0.]
 [  0.   0. 742. ...   0.   0. 709.]
 [554.   0. 980. ...   0.   0. 654.]
 ...
 [  0.   0.   0. ...   0. 894.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 983. ...   0.   0.   0.]]


In [17]:
# testing error
ta = model.score(data_test, test_labels)
print(ta)
test_error=1-ta
print(test_error)

0.976
0.02400000000000002


In [18]:
#training error
ta = model.score(data_train, train_labels)
print(ta)
err = 1-ta
print(err)

1.0
0.0


# Part 2

In [19]:
# RBF ( Gaussian kernel; set γ = 0.001)

gaussian_model = SVC(kernel="rbf",gamma= 0.001)

In [20]:
gaussian_model.fit(data_train, train_labels)

D:\Anaconda path\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(gamma=0.001)

In [21]:
sv = gaussian_model.support_vectors_ 
print(len(sv))
print(sv)

6000
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 983. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0. 486.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0. 886.   0.]]


In [22]:
#for training error
ta =gaussian_model.score(data_train, train_labels)
print(ta)
err = 1-ta
print(err)

1.0
0.0


In [23]:
#for testing error
ta =gaussian_model.score(data_test, test_labels)
print(ta)
err = 1-ta
print(err)

0.5
0.5


In [24]:
#Polynomial kernel (set degree =2, coef0 = 1)
model_poly = SVC(kernel="poly", degree=2, coef0 =1)

In [25]:
model_poly.fit(data_train, train_labels)

D:\Anaconda path\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(coef0=1, degree=2, kernel='poly')

In [26]:
sv = model_poly.support_vectors_ 
print(len(sv))
print(sv)

1332
[[  0.   0. 983. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0. 968.   0.]
 ...
 [  0.   0.   0. ...   0. 894.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 983. ...   0.   0.   0.]]


In [27]:
#for training error
ta =model_poly.score(data_train, train_labels)
print(ta)
err = 1-ta
print(err)

0.9995
0.0004999999999999449


In [28]:
#for testing error
ta = model_poly.score(data_test, test_labels)
print(ta)
err = 1-ta
print(err)

0.98
0.020000000000000018
